export const getLoginButton = () => cy.get('#loginBtn');
export const getLogoutButton = () => cy.get('#logoutBtn');
export const getLoginPasswordPrompt = () => cy.get('#loginPasswordPrompt');
export const getLoginEmailPrompt = () => cy.get('#loginEmailPrompt');
export const getLoginEmailInput = () => cy.get('#loginEmailInput');
export const getLoginPasswordInput = () => cy.get('#loginPasswordInput');
export const getNavAccount = () => cy.get('#account');
export const getDashboard = () => cy.get('#dashboard');
export const getMapCatalogue =() => cy.get('#map-catalogue');
export const getCreateMap = () => cy.get('#create-map');
