name: CI Tests

on: 
  pull_request:
    branches: [develop]
  #manual github action trigger with choices to run individual tests
  workflow_dispatch:
    inputs:
      testchoice:
        type: choice
        description: 'Test Type'
        required: true
        options:
        - full
        - unit
        - all

jobs:  
  test-affected-unit:
    uses: ./.github/workflows/tests.yml
    if: ${{ github.event.inputs.testchoice == 'unit' || github.event.inputs.testchoice == 'full'|| github.event.inputs.testchoice == ''}}
    with:
      test: 'affected'
      testtype: 'unit'